### ISSUE TITLE
CSV to Motec

### ISSUE THREAD

**Issue by jLynx** [Arcayik/motec-csv#1]
Hi, would it be possible to do this the other way around, so for instance you give it a CSV file and it spits out a motec file that can be opened in the motec software?

**Comment by brojob48** [comment]
Im looking for the same thing, at the moment i use race studio 3 and Unipro analyzer for kart data analysis, i wanted to compare data from different dashes, i can export the CSV but i want to open them on Motec.

**Comment by jLynx** [comment]
@brojob48 I found this which solved my problem https://github.com/stevendaniluk/MotecLogGenerator
